### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'descriptor' of CodegenContext.intoPackagePart must not be null

### ISSUE THREAD

**Issue by hrj** [JetBrains/kotlin-eclipse#65]
While running the kotlin plugin in Eclipse Mars (latest milestone), I see this exception trace in `stdout` of eclipse.

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'descriptor' of org/jetbrains/kotlin/codegen/context/CodegenContext.intoPackagePart must not be null
	at org.jetbrains.kotlin.codegen.context.CodegenContext.intoPackagePart(CodegenContext.java)
	at org.jetbrains.kotlin.codegen.PackageCodegen.generate(PackageCodegen.java:297)
	at org.jetbrains.kotlin.codegen.PackageCodegen.generate(PackageCodegen.java:214)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:80)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:67)
	at org.jetbrains.kotlin.core.asJava.KotlinLightClassGeneration.buildLightClasses(KotlinLightClassGeneration.java:53)
	at org.jetbrains.kotlin.core.filesystem.KotlinFileStore.openInputStream(KotlinFileStore.java:48)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:834)
	at org.eclipse.core.internal.resources.File.getContents(File.java:269)
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsByteArray(Util.java:1135)
	at org.eclipse.jdt.internal.core.ClassFile.getBinaryTypeInfo(ClassFile.java:309)
	at org.eclipse.jdt.internal.core.ClassFile.getBinaryTypeInfo(ClassFile.java:282)
	at org.eclipse.jdt.internal.core.ClassFile.buildStructure(ClassFile.java:91)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:259)
	at org.eclipse.jdt.internal.core.SourceRefElement.generateInfos(SourceRefElement.java:107)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.BinaryType.getElementInfo(BinaryType.java:287)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.find(SearchableEnvironment.java:113)
	at org.eclipse.jdt.internal.core.SearchableEnvironment.findType(SearchableEnvironment.java:283)
	at org.eclipse.jdt.internal.core.CancelableNameEnvironment.findType(CancelableNameEnvironment.java:50)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:144)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1184)
	at org.eclipse.jdt.internal.core.util.BindingKeyResolver.getCompilationUnitDeclaration(BindingKeyResolver.java:596)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.beginToCompile(CompilationUnitResolver.java:229)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:857)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:585)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:795)
	at org.eclipse.jdt.core.dom.ASTParser.createBindings(ASTParser.java:1057)
	at org.jetbrains.kotlin.core.resolve.lang.java.EclipseJavaClassFinder.createTypeBinding(EclipseJavaClassFinder.java:132)
	at org.jetbrains.kotlin.core.resolve.lang.java.structure.EclipseJavaPackage.getClassesInPackage(EclipseJavaPackage.java:107)
	at org.jetbrains.kotlin.core.resolve.lang.java.structure.EclipseJavaPackage.getClasses(EclipseJavaPackage.java:62)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyPackageFragmentScopeForJavaPackage.getClassNames(LazyPackageFragmentScopeForJavaPackage.kt:87)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaMemberScope.computeDescriptors(LazyJavaMemberScope.kt:306)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyPackageFragmentScopeForJavaPackage.getDescriptors(LazyPackageFragmentScopeForJavaPackage.kt:117)
	at org.jetbrains.kotlin.resolve.scopes.ChainedScope.getDescriptors(ChainedScope.kt:65)
	at org.jetbrains.kotlin.resolve.NoSubpackagesInPackageScope.getDescriptors(NoSubpackagesInPackageScope.kt:34)
	at org.jetbrains.kotlin.resolve.scopes.ChainedScope.getDescriptors(ChainedScope.kt:65)
	at org.jetbrains.kotlin.resolve.scopes.WritableScopeImpl.getDescriptors(WritableScopeImpl.kt:105)
	at org.jetbrains.kotlin.resolve.scopes.WritableScopeImpl.getDescriptors(WritableScopeImpl.kt:105)
	at org.jetbrains.kotlin.resolve.scopes.ScopesPackage$JetScope$9e70ac16.getDescriptorsFiltered(JetScope.kt:92)
	at org.jetbrains.kotlin.resolve.scopes.ScopesPackage.getDescriptorsFiltered(JetScope.kt:1)
	at org.jetbrains.kotlin.idea.codeInsight.ReferenceVariantsHelper.addCallableExtensions(ReferenceVariantsHelper.kt:204)
	at org.jetbrains.kotlin.idea.codeInsight.ReferenceVariantsHelper.getReferenceVariantsNoVisibilityFilter(ReferenceVariantsHelper.kt:107)
	at org.jetbrains.kotlin.idea.codeInsight.ReferenceVariantsHelper.getReferenceVariants(ReferenceVariantsHelper.kt:62)
	at org.jetbrains.kotlin.ui.editors.codeassist.KotlinCompletionProcessor.getReferenceVariants(KotlinCompletionProcessor.java:161)
	at org.jetbrains.kotlin.ui.editors.codeassist.KotlinCompletionProcessor.generateBasicCompletionProposals(KotlinCompletionProcessor.java:135)
	at org.jetbrains.kotlin.ui.editors.codeassist.KotlinCompletionProcessor.computeCompletionProposals(KotlinCompletionProcessor.java:110)
	at org.eclipse.jface.text.contentassist.ContentAssistant$5.run(ContentAssistant.java:1904)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1902)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:499)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:384)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3790)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3428)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1112)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:993)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by goodwinnk** [comment]
I moved your issue to our tracker: https://youtrack.jetbrains.com/issue/KT-7220
Please add a comment with Kotlin source file you had in your project at the moment of exception.
